# Generated by Django 5.0.4 on 2024-04-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_account", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["personal_account"],
            },
        ),
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("type_service", models.CharField(max_length=255)),
                (
                    "scope_service",
                    models.DecimalField(decimal_places=5, default=0, max_digits=255),
                ),
                ("units", models.CharField(max_length=255)),
                (
                    "tariff",
                    models.DecimalField(decimal_places=5, default=0, max_digits=255),
                ),
                (
                    "accrued_tariff",
                    models.DecimalField(decimal_places=5, default=0, max_digits=255),
                ),
                (
                    "recalculations",
                    models.DecimalField(decimal_places=5, default=0, max_digits=255),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=5, default=0, max_digits=255),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_info_rent",
                        to="rent.rent",
                    ),
                ),
            ],
            options={
                "ordering": ["type_service", "date"],
            },
        ),
    ]
