# Generated by Django 5.0.7 on 2024-08-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceinfo",
            options={"ordering": ["rent", "date"]},
        ),
    ]
