# Generated by Django 5.0.14 on 2025-07-31 14:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epd_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='tariff',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tariff rate per unit', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Tariff'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Volume of service consumed', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Volume'),
        ),
    ]
