# Generated by Django 5.0.14 on 2025-08-02 13:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epd_parser", "0003_alter_epddocument_insurance_amount_meterreading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecharge",
            name="recalculation",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Recalculation amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Recalculation",
            ),
        ),
    ]
