# Generated by Django 5.0.14 on 2025-08-03 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epd_parser", "0005_add_unit_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epddocument",
            name="pdf_file",
        ),
    ]
