# Generated by Django 5.2.4 on 2025-08-04 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epd_parser", "0008_alter_epddocument_due_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FlexibleServiceCharge",
        ),
    ]
