# Generated by Django 5.2.4 on 2025-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epd_parser", "0009_remove_flexible_service_charge"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="epddocument",
            index=models.Index(
                fields=["created_at"], name="epd_parser__created_ed11a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="epddocument",
            index=models.Index(
                fields=["account_number", "created_at"],
                name="epd_parser__account_be8d16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="epddocument",
            index=models.Index(
                fields=["payment_period", "created_at"],
                name="epd_parser__payment_15042a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["document", "order"], name="epd_parser__documen_a65c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["service_name", "meter_number"],
                name="epd_parser__service_f73563_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recalculation",
            index=models.Index(
                fields=["document", "order"], name="epd_parser__documen_364abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recalculation",
            index=models.Index(
                fields=["service_name", "amount"], name="epd_parser__service_30878f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecharge",
            index=models.Index(
                fields=["document", "service_name"],
                name="epd_parser__documen_ca1247_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicecharge",
            index=models.Index(
                fields=["service_name", "total"], name="epd_parser__service_e24dae_idx"
            ),
        ),
    ]
