# Generated by Django 5.0.4 on 2026-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_insurance_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
